Add unit test GitHub Action, add dummy service to linter

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -1,13 +1,11 @@
-name: Lint with pylint
+name: Run Pytest
+
 on:
-  push:
-    branches:
-      - 'main'
   pull_request:
+
 jobs:
-  lint:
+  build:
     runs-on: ubuntu-latest
-    name: Lint
     defaults:
       run:
         shell: bash -el {0}
@@ -24,7 +22,7 @@ jobs:
       - name: Install python dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install pytest pylint==2.17.5 numpy==1.24.3 flask==2.3.2 flask-cors==4.0.0 python-dateutil==2.8.2 pint==0.21 importlib-metadata==6.7.0 jsonschema==4.19.0 pika==1.3.1
+          pip install pytest pytest-cov pylint==2.17.5 python-dateutil==2.8.2
 
       - name: Checkout idss-engine-commons
         uses: actions/checkout@v2
@@ -37,16 +35,22 @@ jobs:
         working-directory: commons/python/idsse_common
         run: pip install .
 
-      - name: Set PYTHONPATH for pylint
-        run: |
-          echo "PYTHONPATH=python/idsse/testing/" >> $GITHUB_ENV
-
-      - name: Run code linter
-        run: pylint ./python/idsse/testing --max-line-length=120 --recursive true
-
-      - name: Set PYTHONPATH for dummy service
+      - name: Set PYTHONPATH for pytest
         run: |
           echo "PYTHONPATH=python/nwsc_dummy_service" >> $GITHUB_ENV
 
-      - name: Run code linter for dummy service
-        run: pylint ./python/nwsc_dummy_service --max-line-length=120 --recursive true
+      - name: Test pytest
+        working-directory: python/nwsc_dummy_service/test
+        run: |
+          set -o pipefail;  # exit immediately if pytest fails (tee obfuscates the exit code)
+          pytest --cov=.. --cov-report=term --junitxml=./pytest.xml | tee ./coverage.txt;
+
+      - name: Pytest coverage comment
+        if: ${{ github.ref == 'refs/heads/main' }}
+        id: coverageComment
+        uses: MishaKav/pytest-coverage-comment@main
+        with:
+          hide-comment: true
+          badge-title: Coverage
+          title: Report
+          pytest-coverage-path: python/nwsc_dummy_service/test/coverage.txt
